### PR TITLE
Changes for CUDA 9.0 float16 support.

### PR DESCRIPTION
**Pull request by abergeron**
This integrates the relevant parts of #485 with the changes in #499.

#499 should be merged first.

### CODE REVIEW

**Comment by borisfom** [comment]
@abergeron : looks good to me.

**Comment by borisfom** [comment]
@abergeron : what is your setup? We also have collectives crash (garbage returned in the key on init) for a long time.

**Comment by nouiz** [comment]
IRL discussion, he use cuda9. On cuda8 I have the crash too. As we can
reproduce it, we probably can make it work.

**Comment by abergeron** [comment]
Apparently the buffer code was broken, so I just removed it.  It was just fancy code to be able to modify the value of the ID directly, but we can still get and set it as a bytearray from the `.comm_id` property so it's not a great loss.

**Comment by borisfom** [comment]
Thanks @abergeron

**Comment by borisfom** [comment]
Thanks @abergeron !

**Comment by nouiz** [comment]
@tsirif what do you think about the crash fix?

We need to make the release, so merging. But if needed, this can be added back later.

**Comment by tsirif** [comment]
No, I do not think it is needed either, probably I should not have put that in the first place.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
