### PR TITLE
Remove include that break cuda8 and isn't need anymore in cuda9.

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by nouiz** [comment]
Don't merge. My local tests with cuda9 fail.

**Comment by abergeron** [comment]
With my commit it fixes the problem in the pygpu tests.

**Comment by nouiz** [comment]
I still have problems:

```
$ DEVICE=cuda0 nosetests pygpu.tests.test_collectives
*** Testing for GeForce GTX 750
mpi4py found: True
*** Collectives testing for GeForce GTX 750
E....
======================================================================
ERROR: test suite for <class 'pygpu.tests.test_collectives.TestGpuComm'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/u/bastienf/.local/lib/python2.7/site-packages/pygpu-0.7.0-py2.7-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 105, in setUpClass
    cls.gpucomm = GpuComm(cls.cid, cls.size, cls.rank)
  File "pygpu/collectives.pyx", line 109, in pygpu.collectives.GpuComm.__cinit__ (pygpu/collectives.c:3630)
GpuArrayException: ncclCommInitRank: unhandled cuda error

----------------------------------------------------------------------
Ran 4 tests in 0.017s

FAILED (errors=1)
```

What this could be? Probably my env that is troublesome, but we should at least 2 person can make it work and give a good error.

**Comment by nouiz** [comment]
Merging. Old driver on some computer with very bad errors!

**Pull request merged**
