### PR TITLE
pygpu/tests: Skip tests that require CUDA context if the context is not CUDA

### LINKED ISSUE #491: Skip CUDA specific tests if DEVICE is not CUDA compatible
I have successfully enabled integration tests for the packaged version of `libgpuarray` on Debian. The `pygpu` test suite is run on `pocl`, a CPU implementation of OpenCL, with most tests [passing](http://debomatic-amd64.debian.net/distribution#unstable/libgpuarray/0.6.9-2/autopkgtest).

However, the test suite attempts to run CUDA specific tests although DEVICE is set to `opencl0:0`, resulting in many errors of the form:
```
TypeError: This is for CUDA arrays.
```

Please consider adapting the test suite so that those CUDA tests aren't performed if the selected device has got no CUDA compute. This should be achievable via something like `pytest` [skipif](https://docs.pytest.org/en/latest/skipping.html#id1).

### PR DESCRIPTION
**Pull request by jvesely**
Fixes #491
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Comment by jvesely** [comment]
@nouiz, are you interested in bug fixes?

**Comment by abergeron** [comment]
Yes we are, however I would fix this differently.  The only part of those tests that require a cuda context is the .gpudata access.  You could make that part conditional on the context kind and the rest should pass.

**Comment by nouiz** [comment]
@abergeron this PR was updated. Can you review it again?
@jvesely when you update a commit and force push, this do not send a notification. So if you can make  comment, it will make us see the change faster.

**Comment by jvesely** [comment]
thanks. I didn't know new commits were silent.

**Pull request merged**
