### PR TITLE
Fix call of elemwise in the basic case when using scalars.

### PR DESCRIPTION
**Pull request by abergeron**
There was an index bug which would cause the library to crash in that case.  I've fixed it and added a test for that.

### CODE REVIEW

**Comment by abergeron** [comment]
Fixes #296

**Comment by nouiz** [comment]
ok to merge when jenkins pass

**Comment by nouiz** [comment]
There is a temporary problem with jenkins that made it fail.

**Comment by nouiz** [comment]
jenkins test this

**Pull request merged**
