### PR TITLE
Add offset handling for indices and result in take1()

### PR DESCRIPTION
**Pull request by abergeron**
fix gh-https://github.com/Theano/Theano/issues/5285

### CODE REVIEW

**Comment by abergeron** [comment]
I need some tests for the new case.  They will come later.

**Comment by nouiz** [comment]
Is there a bug report for this? If so, can you link to it?

**Comment by nouiz** [comment]
seem good.

**Comment by nouiz** [comment]
I added a link to what it fix.

**Comment by abergeron** [comment]
Now I have a test.

**Pull request merged**
