### PR TITLE
Rewrite the FindCheck script.

### PR DESCRIPTION
**Pull request by abergeron**
Fix the odd problems that where popping due to it not respecting cmake conventions with its output.

### CODE REVIEW

**Comment by nouiz** [comment]
I get this error while compiling:

```
Linking C static library ../../lib/libgpuarray-static.a
[ 77%] Built target gpuarray-static
Scanning dependencies of target check_array
[ 79%] Building C object tests/CMakeFiles/check_array.dir/main.c.o
[ 81%] Building C object tests/CMakeFiles/check_array.dir/check_array.c.o
Linking C executable check_array
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcheck.a(check_run.o): undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
//lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tests/CMakeFiles/check_array.dir/build.make:116: recipe for target 'tests/check_array' failed
make[2]: *** [tests/check_array] Error 1
CMakeFiles/Makefile2:187: recipe for target 'tests/CMakeFiles/check_array.dir/all' failed
make[1]: *** [tests/CMakeFiles/check_array.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by abergeron** [comment]
On which machine?

**Comment by nouiz** [comment]
leto18

**Comment by abergeron** [comment]
I've updated this PR to fix the problem and pushed the commits, but for some reason they don't appear on the website.   This might be linked with the outage today.

**Comment by abergeron** [comment]
The new commits are up now!

**Comment by nouiz** [comment]
It work for me, so merging.

**Pull request merged**
