### PR TITLE
New faster call protocol

### PR DESCRIPTION
**Pull request by abergeron**
This removes most of the overhead for kernel calls and makes the interface more extensible.

It also enables the reservation of dynamic shared memory for kernels that need it.

### CODE REVIEW

**Comment by nouiz** [comment]
We need a way for Theano to tell that the version of gpuarray is too old and tell user to update it. Is there a version number that you can bump and make Theano check it?

**Comment by nouiz** [comment]
I have this error:

"
[bastienf@oolong libgpuarray]$python setup.py install --user
Compiling pygpu/gpuarray.pyx because it changed.
Compiling pygpu/blas.pyx because it depends on ./pygpu/gpuarray.pxd.
Cythonizing pygpu/gpuarray.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    if res is NULL:
        raise GpuArrayException, "Invalid kernel or destroyed context"
    return res

cdef int kernel_sched(GpuKernel k, size_t n, size_t *ls, size_t *gs) except -1:
    cdef int err;
               ^
------------------------------------------------------------

pygpu/gpuarray.pyx:461:16: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 104, in <module>
    ext_modules=cythonize(exts),
  File "/Tmp/lisa/os_v3/canopy/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 753, in cythonize
    cythonize_one(*args[1:])
  File "/Tmp/lisa/os_v3/canopy/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 820, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pygpu/gpuarray.pyx
"

**Comment by nouiz** [comment]
Other then that I think it is ok. I'll need to run the tests when the compilation error is fixed.

**Comment by nouiz** [comment]
Did you timmed the speed up? What numbers do you get?

If you don't have them, don't spend time on getting them, i'm confident it will at least not slow down computation and it more general, so this is good.

**Comment by nouiz** [comment]
If I fix the compilation error myself, I get many errors like this:

```
$DEVICE=cuda0 nosetests -x
*** Testing for GeForce GTX 750 Ti
...........................................................................................................................................................................................................................................................................................................................E
======================================================================
ERROR: pygpu.tests.test_elemwise.test_elemwise1_ops_array(<built-in function neg>, 'float32')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/u/bastienf/.local/lib/python2.7/site-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/u/bastienf/.local/lib/python2.7/site-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_elemwise.py", line 40, in elemwise1_ops_array
    assert numpy.allclose(out_c, numpy.asarray(out_g))
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
  File "gpuarray.pyx", line 1419, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:15770)
  File "gpuarray.pyx", line 1242, in pygpu.gpuarray.pygpu_as_ndarray (pygpu/gpuarray.c:13833)
  File "gpuarray.pyx", line 394, in pygpu.gpuarray.array_read (pygpu/gpuarray.c:5479)
GpuArrayException: Unknown error code

----------------------------------------------------------------------
Ran 316 tests in 2.940s

FAILED (errors=1)

```

**Comment by abergeron** [comment]
I didn't time the speedup and I don't expect it to be very large, but we do remove two copies of the parameters which should help anyway.

Also, I've fixed the problems in pygpu and the tests are passing now.

**Comment by abergeron** [comment]
And it's done.

**Pull request merged**
