### PR TITLE
Two fixes and a suggestion for check_args()

### PR DESCRIPTION
**Pull request by davidweichiang**
Hi, the first two commits fix bugs in check_args that are described in the commit messages. The third commit is just a suggestion: this function computes information that never gets used in the contiguous case (which is presumably also the most common), so a simplified version check_contig only computes what is needed, and is faster.

### CODE REVIEW

**Comment by davidweichiang** [comment]
I forgot to add, if check_contig is kept, then the contiguity check in check_args could be removed. But I wasn't sure whether that would mess up the collapse=None case.

**Comment by abergeron** [comment]
I lke check_contig so ok for that.

If you are interested, this function could use some tests that make sure it works correctly.  The cases you mentioned here could make a good starting point.  The only exception is that the (1, 1) case should reduce to (1,), not ().

**Comment by davidweichiang** [comment]
OK, done. Thanks!

Do you have any thoughts on whether the contiguity check can be removed from check_args so as not to repeat work?

**Comment by abergeron** [comment]
Yes it does "duplicate" work, but it's still useful to know that the inputs are contiguous in each case since it supports the `collapse=None` option.  If you can find a way to pass in the information then it may be useful to remove that check but I feel that it is too much effort for little gain.

**Comment by davidweichiang** [comment]
Thanks! In `select_kernel`, `check_args` is called only in the discontiguous case, so `collapse=True` can be used instead. But if {`call_basic`, `call_dimspec`, `call_specialized`} are called directly, this is not true. However, I'm uncertain whether it makes sense to call `call_basic(..., collapse=None)`, etc. My hunch is that it does not, in which case I think that the `collapse=None` option could be removed. Is that right?

Or, is there a reason the following wouldn't work: in `check_args`,if `collapse=True`, and the arguments are detected to be contiguous, return `size, 1, size, (itemsize,)*len(args), offsets, True` as a special case. Then I think neither `check_contig` nor `collapse=None` would be needed.

**Comment by abergeron** [comment]
Yes it does make sense to use collapse=None since you can reuse a basic kernel when contiguous (to avoid recompiling too often), but still get massive speedup by working on a vector from the point of view of the kernel.  The indexing code is quite costly.

Your second case could also work, yes, but I would make that `if collapse or collapse is None` since I don't want to drop support for that argument unexpectedly.  It doesn't cost much to keep it in.  Feel free to make a new PR with that.

**Comment by davidweichiang** [comment]
Sorry, I don't quite understand yet -- as far as I can see, `basic_kernel` doesn't have a codepath to treat contiguous arrays specially. So I'm not seeing where `call_basic(..., collapse=None)` would get the speedup.

**Comment by abergeron** [comment]
The codepath that does this is inside `check_args()`.  The speedup comes from the fact that after collapsing you only have a 1D array which is much faster to work with than 2D or 3D (or more).

**Comment by davidweichiang** [comment]
I tried idea number 2 (exit `check_args` early if contiguous) and it was not as fast as the current version, so I like the current version better.

However, I'm still trying to understand the `collapse=None` option. I gather that the purpose of this option was to collapse a contiguous multiway array into a vector without actually going through the costly collapsing logic. But this optimization requires the caller to check the return value and select the appropriate kernel. Thus,

-  `ElementwiseKernel.__call__` now checks contiguity using `check_contig` and calls `check_args` only if discontiguous, in which case `collapse=None` and `collapse=True` are equivalent. So this case performs well, but doesn't need `collapse=None`.
- `ElementwiseKernel.call_basic` and friends call `check_args` unconditionally and ignore the `contig` flag returned by it. So if `k` is an `ElementwiseKernel` and `a` is a 10-dimensional contiguous array, and I call `k.call_basic(a, collapse=None)`, it will do slow 10-dimensional indexing -- but if I call `k.call_basic(a[...,0], collapse=None)`, it will collapse all 9 dimensions and do 1-dimensional indexiing! I can't think of any reason why that would be desired. It would seem faster to use `collapse=True` instead.

Thanks for your patience!

**Comment by abergeron** [comment]
Yes it does ignore the contig flag, but not the returned dimensions and strides which is what the collapsing code modifies.

Also, `collapse=None` was introduce as a sort of "collapse-light" mode that would only run the expansive collapsing code if it can guarantee significant benefits from it (i.e the array is contiguous so everything will be collapsed).  It may not be useful in all cases and certainly not if you know exactly what your data is and how much you have to gain.

I don't see why there would be collapsing for `a[...,0]`, but not for `a` in your example though.

**Comment by davidweichiang** [comment]
For `collapse=None`, collapsing occurs iff the array is _not_ contiguous (right?), so since `a` is contiguous but `a[...,0]` is not, the former will not be collapsed but the latter will.

**Comment by abergeron** [comment]
No it only occurs iff the array is contiguous.

**Comment by davidweichiang** [comment]
But...the docstring says: If `collapse` is None dimension collapsing will be performed if some arguments are non-contiguous.

And the code says:

    if not contig and collapse is None:
        ...
        collapse = True

**Comment by abergeron** [comment]
Oh, you're right.  So yeah, this means `collapse=None` should map to `collapse=True` in all cases, so we can probably remove the contiguous check.  I somehow remember it being the opposite way ...

Sorry about that.

**Pull request merged**
