### PR TITLE
cluda_opencl: Use round to nearest even to match cpu version

### LINKED ISSUE #462: Failure in test_elemwise_f16 add/iadd
Running into failures with `test_elemwise_f16` using `add` and `iadd`. Am running on macOS 10.11.6 on a MacBook Pro (Retina, 15-inch, Late 2013). Details from the test run and environment shown below.

Test run:

<details>

```
DEVICE="opencl0:0" python -c "import pygpu; pygpu.test()"
pygpu is installed in /zopt/conda2/envs/pygpu/lib/python2.7/site-packages/pygpu
NumPy version 1.12.1
NumPy relaxed strides checking option: True
NumPy is installed in /zopt/conda2/envs/pygpu/lib/python2.7/site-packages/numpy
Python version 2.7.13 | packaged by conda-forge | (default, May  2 2017, 13:29:36) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
nose version 1.3.7
*** Testing for Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
...S.....................................................................OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a == b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a == b);
       ~ ^  ~


.......OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a != b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a != b);
       ~ ^  ~


.......OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a < b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a < b);
       ~ ^ ~


.......OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a <= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a <= b);
       ~ ^  ~


.......OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a > b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a > b);
       ~ ^ ~


.......OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'char' and 'ulong' (aka 'unsigned long')
res = (a >= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:56:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a >= b);
       ~ ^  ~


...........................................................................FF..................................................................................................OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a == b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a == b);
       ~ ^  ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a == b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a == b);
       ~ ^  ~


...........OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a != b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a != b);
       ~ ^  ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a != b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a != b);
       ~ ^  ~


...........OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a < b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a < b);
       ~ ^ ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a > b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a < b);
       ~ ^ ~


...........OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a <= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a <= b);
       ~ ^  ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a >= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a <= b);
       ~ ^  ~


...........OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a > b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a > b);
       ~ ^ ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a < b);
       ~ ^ ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a > b);
       ~ ^ ~


...........OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'char' and 'uint' (aka 'unsigned int')
res = (a >= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a >= b);
       ~ ^  ~


OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'long'
res = (a <= b);
       ~ ^  ~


..OpenCL Build Warning : Compiler build log:
<program source>:54:10: warning: comparison of integers of different signs: 'ulong' (aka 'unsigned long') and 'char'
res = (a >= b);
       ~ ^  ~


..............................................................................................................................................................OpenCL Build Warning : Compiler build log:
<program source>:44:1: warning: no previous prototype for function 'infinity'
infinity() {return INFINITY;}
^
<program source>:47:1: warning: no previous prototype for function 'neg_infinity'
neg_infinity() {return -INFINITY;}
^


OpenCL Build Warning : Compiler build log:
<program source>:44:1: warning: no previous prototype for function 'infinity'
infinity() {return INFINITY;}
^
<program source>:47:1: warning: no previous prototype for function 'neg_infinity'
neg_infinity() {return -INFINITY;}
^


OpenCL Build Warning : Compiler build log:
<program source>:45:1: warning: no previous prototype for function 'infinity'
infinity() {return INFINITY;}
^
<program source>:48:1: warning: no previous prototype for function 'neg_infinity'
neg_infinity() {return -INFINITY;}
^


OpenCL Build Warning : Compiler build log:
<program source>:45:1: warning: no previous prototype for function 'infinity'
infinity() {return INFINITY;}
^
<program source>:48:1: warning: no previous prototype for function 'neg_infinity'
neg_infinity() {return -INFINITY;}
^


.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................OpenCL Build Warning : Compiler build log:
<program source>:56:27: warning: comparison of integers of different signs: 'int' and 'ulong' (aka 'unsigned long')
    if ((ii0 < 0) || (ii0 >= d0)) {
                      ~~~ ^  ~~


.OpenCL Build Warning : Compiler build log:
<program source>:56:27: warning: comparison of integers of different signs: 'int' and 'ulong' (aka 'unsigned long')
    if ((ii0 < 0) || (ii0 >= d0)) {
                      ~~~ ^  ~~


.OpenCL Build Warning : Compiler build log:
<program source>:56:27: warning: comparison of integers of different signs: 'int' and 'ulong' (aka 'unsigned long')
    if ((ii0 < 0) || (ii0 >= d0)) {
                      ~~~ ^  ~~


..................................................................................................................................................................................................................................
======================================================================
FAIL: pygpu.tests.test_elemwise.test_elemwise_f16(<built-in function add>, 'float16', 'float16', (50,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/pygpu/tests/test_elemwise.py", line 123, in elemwise2_ops_array
    assert numpy.allclose(out_c, numpy.asarray(out_g))
AssertionError

======================================================================
FAIL: pygpu.tests.test_elemwise.test_elemwise_f16(<built-in function iadd>, 'float16', 'float16', (50,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/zopt/conda2/envs/pygpu/lib/python2.7/site-packages/pygpu/tests/test_elemwise.py", line 146, in ielemwise2_ops_array
    assert numpy.allclose(out_c, numpy.asarray(out_g), atol=1e-6)
AssertionError

----------------------------------------------------------------------
Ran 6709 tests in 57.061s

FAILED (SKIP=1, failures=2)
```

</details>

<br>

Environment:

<details>

```yaml
name: pygpu
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_1
- blas=1.1=openblas
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py27_0
- decorator=4.0.11=py27_0
- enum34=1.1.6=py27_1
- ipython=5.4.1=py27_0
- ipython_genutils=0.2.0=py27_0
- libgfortran=3.0.0=0
- libgpuarray=0.6.5=np112py27_0
- mako=1.0.6=py27_0
- markupsafe=1.0=py27_0
- ncurses=5.9=10
- nose=1.3.7=py27_2
- numpy=1.12.1=py27_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2k=0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- pygpu=0.6.5=0
- python=2.7.13=1
- readline=6.2=0
- scandir=1.5=py27_1
- setuptools=33.1.1=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_1
- sqlite=3.13.0=1
- tk=8.5.19=1
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>

### PR DESCRIPTION
**Pull request by jvesely**
Fixes test_elemwise_f16 add/iadd on amdgcn and possibly other OpenCL
implementations.
Fixes #462

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Comment by jvesely** [comment]
See also https://bugs.freedesktop.org/show_bug.cgi?id=100105

**Comment by jvesely** [comment]
It's also possible to use vstore_half() and use the default rounding mode (rte, and should be faster).

**Comment by jvesely** [comment]
@nouiz, are you interested in bug fixes?

**Comment by nouiz** [comment]
I let this to @abergeron. He was in vacation, but he his back.

**Pull request merged**
