### PR TITLE
Implicitly left-pad with broadcastable dims

### PR DESCRIPTION
**Pull request by lamblin**
No tests yet, but it seems to solve an issue in Theano with GpuIncSubtensor.

### CODE REVIEW

**Comment by abergeron** [comment]
You just need to remove the WIP tag so that jenkins can have a crack at it.

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by lamblin** [comment]
Discussed IRL: @abergeron will add a test.

**Comment by abergeron** [comment]
Now this has a (small) test.

**Pull request merged**
