### PR TITLE
Prevent redefinition of max_align_t

### PR DESCRIPTION
**Pull request by mdda**
This addresses issue #55 (and fixes a couple of typos, and cures a spurious warning).

### CODE REVIEW

**Comment by rmsc** [comment]
I just proposed a similar pull, failed to notice this one.

First of all, I would avoid mixing unrelated changes in the same commit (that is, the max_align_t thing and the unrelated typos).

Second, after the ifndef you should insert a define, just as it's done on the stddef.h header. Otherwise if the file is included more than once, you'll get an error.

**Comment by mdda** [comment]
I'll add the extra define if you like, but note that this is in a .c file, so no-one is including it anywhere...

If you don't like the typo fixes, then I'll resubmit from a blank slate (after all, this is a 2 line fix for the max_align_t issue).  The typos would then have to wait (which, apparently, is a thing).

**Comment by abergeron** [comment]
I think this is all fine, but the PR needs a rebase (for some reason).

**Comment by abergeron** [comment]
Actually it seems that PR #58 already fixes the max_align_t problem and that is the conflict.

**Comment by abergeron** [comment]
The max_align_t issue has been fixed for a while, so I'll close this PR.

**Pull request closed without merging**
